* SARTA RTA Code Readme

SARTA is an infrared radiative transfer code that simulates radiances
measured by the following operational infrared sounders:

| Instrument      | Platform                        |
|-----------------+---------------------------------|
| AIRS            | NASA EOS-AQUA                   |
|-----------------+---------------------------------|
| CrIS Normal Res | NASA/NOAA NPP                   |
| CrIS High Res   | NASA/NOAA NPP + upcoming JPSS-1 |
|-----------------+---------------------------------|
| IASI            | EUMETSAT METOP                  |

This repo is a new start for sarta development and generation of
production executables and only includes revision history start in
2016 for the CrIS sensor.  The AIRS, IASI, and CrIS Normal
Res RTA do compile with this source code, but test data comparing
kCARTA truth radiances to fast SARTA radiances does not exist for
these sensors.  

Selection of sensor type is done using src/incFTC* files, see Makefile
and make_sarta for details.

The test directory contains a Matlab mfile for testing the CrIS High
Res version of SARTA (named crisg4_oct16 in the Makefile) called
cris_hires_bias_test.m.  It reads in the regression profiles
(including various secant angles) and writes out a rtp file with the
computed radiances.  See test/Figs/ for the graph of biases and
standard deviations created by this mfile.  

The rtp files in test for IASI, AIRS, and CrIS Normal resolution
(test_iasi_1,_2.rtp, test_airs.rtp, and test_cris_lowres.rtp) are just
the output of the relevant SARTA RTA for some arbitrary profiles.  If
you want to compare your version of SARTA to these, read in the rtp
files, delete prof.rcalc, save the rtp file, and run SARTA on this
file.  Compare the output of your run to prof.rcalc in the supplied
file. 

* Libraries

If you want to use the rtp interface to SARTA you will need our rtp
library available at https://github.com/strow/rtp.  You will also need
the publically available HDF-4 libraries.

* Documentation

See the docs directory for details.  This documentation is quite old,
although =Docs/last_update.txt= has an entry for this version.  

* Getting Started

These are fairly generic instructions, but tailored to a specific branch (jpl) which has a tailored Makefile.  Sarta will not run without the fast transmittance coefficient files.  Contact L. Strow (strow@umbc.edu) for access to these files.

Sarta is built in the src directory.  The makefiles are pretty generic.  src/Makefile drives the build, which in turn calls =make_sarta= to build the clear sky version of sarta or =make_sarta_pclsam= to make the cloudy scattering version of sarta.  These two makefiles contain choices of compilers, etc. and rename the output files if you desire.

** Versions Available

- m140_icebaumGHM_waterdrop_desertdust :: The scattering version of sarta for AIRS using coefficients from 2008.

- apr08_m140_wcon_nte_2016tuning :: The clear version of sarta for AIRS using a recently derived tuning table and coefficients from 2008.

- apr08_m140_pge_v6_tunmlt :: The opertional version of the AIRS RTA but only for a focal plane offset of -14 microns.  Other focal plane offsets can be selected by changing the incFTC* files.

- crisg4_nov09_wcon_nte :: A CrIS version of sarta for clear scenes using the CrIS nominal spectral resolution.  The coefficients are circa 2008, same as AIRS above.

- crisg4_oct16 :: A new version of SARTA for CrIS in extended resolution mode, using new spectroscopy (circa 2016).  This version is used in the NOAA NUCAPS operational retrieval system.

- iasi_may09_wcon_nte :: Version of SARTA clear scene for IASI, using 2008 spectroscopy (same as AIRS and CrIS nominal spectral resolution modes).  


** Testing

=sarta/test= has various files for testing.  These will be further documented and developed in the future.  To test the AIRS version of sarta:

Create the executable and place it in the =bin= directory (optional). Execute sarta and input the file =test/Airs/sarta_in.rtp as shown below

=../../bin/sarta_apr08_m140_wcon_nte_2016tuning fin= = =sarta_in.rtp fout= = =yourfileout.rtp=  (No spaces between fin, fout, and the filenames).

Compare this to =src/test/Airs/sarta_out_clear.rtp=.  Follow the same procedure for the scattering version of sarta, but compare to =test/Airs/sarta_out_cloudy.rtp=. 

A number of test files for CrIS are in =test/Cris=.

