* SARTA RTA Code Readme

SARTA is an infrared radiative transfer code that simulates radiances
measured by the following operational infrared sounders:

| Instrument      | Platform                        |
|-----------------+---------------------------------|
| AIRS            | NASA EOS-AQUA                   |
|-----------------+---------------------------------|
| CrIS Normal Res | NASA/NOAA NPP                   |
| CrIS High Res   | NASA/NOAA NPP + upcoming JPSS-1 |
|-----------------+---------------------------------|
| IASI            | EUMETSAT METOP                  |

This repo is a new start for sarta development and generation of
production executables and only includes revision history start in
2016 for the CrIS sensor.  The AIRS, IASI, and CrIS Normal
Res RTA do compile with this source code, but test data comparing
kCARTA truth radiances to fast SARTA radiances does not exist for
these sensors.  

Selection of sensor type is done using src/incFTC* files, see Makefile
and make_sarta for details.

The test directory contains a Matlab mfile for testing the CrIS High
Res version of SARTA (named crisg4_oct16 in the Makefile) called
cris_hires_bias_test.m.  It reads in the regression profiles
(including various secant angles) and writes out a rtp file with the
computed radiances.  See test/Figs/ for the graph of biases and
standard deviations created by this mfile.  

The rtp files in test for IASI, AIRS, and CrIS Normal resolution
(test_iasi_1,_2.rtp, test_airs.rtp, and test_cris_lowres.rtp) are just
the output of the relevant SARTA RTA for some arbitrary profiles.  If
you want to compare your version of SARTA to these, read in the rtp
files, delete prof.rcalc, save the rtp file, and run SARTA on this
file.  Compare the output of your run to prof.rcalc in the supplied
file. 

* Libraries

If you want to use the rtp interface to SARTA you will need our rtp
library available at https://github.com/strow/rtp.  You will also need
the publically available HDF-4 libraries.

* Documentation

See the docs directory for details.  This documentation is quite old,
although =Docs/last_update.txt= has an entry for this version.  

